ExeFelipeCiprianoFelipeCarvalho/ExeFelipeCiprianoFelipeCarvalho/Controllers/AulaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExeFelipeCiprianoFelipeCarvalho.Controllers
{
    public class AulaController : Controller
    {
        // GET: Aluno
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Aluno()
        {
            if (TempData["Text"] != null)
            {
                ViewBag.Mens = "Os melhores alunos são aqueles que estudam mais!";
                return View();
            }
            else
            {
                ViewBag.Mens = "Os melhores alunos são aqueles que estudam mais!";
                return View();
            }
        }

        public ActionResult Google()
        {
            return Redirect("https://google.com");
        }
    }
}

ExeFelipeCiprianoFelipeCarvalho/ExeFelipeCiprianoFelipeCarvalho/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExeFelipeCiprianoFelipeCarvalho.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewData["Cont"] = "Contato";
            TempData["Text"] = "O MVC é um padrão de desenvolvimento muito utilizado no mundo web é conhecido por 'forçar' o programador a separar as responsabilidades.";
            return View();
        }
    }
}

ExeFelipeCiprianoFelipeCarvalho/ExeFelipeCiprianoFelipeCarvalho/Views/Aula/Aluno.cshtml
@{
    ViewBag.Title = "Estudo";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Estudo</title>
</head>
<body>
    <div>
        <h1>Aluno</h1>
        <h1>@ViewBag.Mens</h1>
        <h1>@TempData["Text"]</h1>
        <h4>@Html.ActionLink("Google", "Google", "Aula")</h4>
    </div>
</body>
</html>

ExeFelipeCiprianoFelipeCarvalho/ExeFelipeCiprianoFelipeCarvalho/Views/Aula/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h1>View sem Layout</h1>
        @Html.ActionLink("Menu", "Index", "Home")
    </div>
</body>
</html>

ExeFelipeCiprianoFelipeCarvalho/ExeFelipeCiprianoFelipeCarvalho/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ExeFelipeCiprianoFelipeCarvalho/ExeFelipeCiprianoFelipeCarvalho/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contato";
}
<h2>@ViewData["Cont"].</h2>
<h3>@Html.ActionLink("Estudo", "Aluno", "Aula")</h3>

ExeFelipeCiprianoFelipeCarvalho/ExeFelipeCiprianoFelipeCarvalho/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ExeFelipeCiprianoFelipeCarvalho/ExeFelipeCiprianoFelipeCarvalho/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Página Inicial", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Sem Layout", "Index", "Aula")</li>
                    <li>@Html.ActionLink("Estudo", "Aluno", "Aula")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>